const products = [
  {
    _id: '1',
    name: 'Samsung Galaxy S20 FE 5G',
    image: '/images/S20FE5G.jpg',
    description:
    "5G Ready powered by Qualcomm Snapdragon 865 Octa-Core processor, 8GB RAM, 128GB internal memory expandable up to 1TB, Android 11.0 operating system and dual SIM",
    brand: 'Samsung',
    category: 'Electronics',
    price:36990.00,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Samsung Galaxy M52 5G',
    image: '/images/samsung M2.jpg',
    description:
    'Triple camera setup-64MP (F 1.8) main camera + 12MP (F2.2) Ultra wide camera+ 5MP (F2.4) depth camera 32MP (F2.2) front camera',
    brand: 'Samsung',
    category: 'Electronics',
    price: 24999.00,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '3',
    name: 'APPLE iPhone 12 (Purple, 128 GB)',
    image: '/images/iphone-12.jpeg',
    description:
      'APPLE iPhone 12 (Purple, 128 GB)128 GB ROM 15.49 cm (6.1 inch) Super Retina XDR Display 12MP + 12MP | 12MP Front Camera A14 Bionic Chip with Next Generation Neural Engine Processor Ceramic Shield Industry-leading IP68 Water Resistance All Screen OLED Display 12MP TrueDepth Front Camera with Night Mode, 4K Dolby Vision HDR Recording',
    brand: 'Apple',
    category: 'Electronics',
    price: 59990,
    countInStock: 10,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Xiaomi 11T Pro 5G',
    image: '/images/Xiaomi 11T Pro 5G.jpg',
    description:
      'Rear Triple Camera Co-Developed by Hasselblad, 48 MP Main camera, 50 MP Ultra Wide Angle Camera with Free Form Lens, 2 MP Monochorme Lens. Also comes with a 16 MP Front Camera Qualcomm Snapdragon 888 Processor with Adreno 660 GPU',
    brand: 'Xiaomi',
    category: 'Electronics',
    price: 19990,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'OnePlus 9 5G',
    image: '/images/OnePlus 9 5G.jpg',
    description:
      'Camera: Sony IMX 766 50MP+8MP+2MP AI Triple Camera with 4K@30FPS|1080p video at 30/60 fps | 32MP Front camera with 1080p video at 30/60 fps | Super Slow Motion: 1080p video at 120 fps, 720p video at 240 fps | Time-Lapse: 1080p 120fps;720p 240fps',
    brand: 'OnePlus',
    category: 'Electronics',
    price: 39990,
    countInStock: 10,
    rating: 4.6,
    numReviews: 12,
  },
  {
    _id: '6',
    name: 'Redmi Note 11',
    image: '/images/Redmi Note 11.jpg',
    description:
      'Camera: 50 MP Quad Rear camera with 8MP Ultra-wide, 2MP Macro and Portrait lens| 13 MP Front camera',
    brand: 'Xiaomi',
    category: 'Electronics',
    price: 29990,
    countInStock: 10,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 120000,
    countInStock: 0,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '8',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 50000,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  
  {
    _id: '9',
    name: 'Cannon EOS 80D DSLR Camera',
    image: '/images/camera.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 350000,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Sony Playstation 4 Pro White Version',
    image: '/images/playstation.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 150000,
    countInStock: 11,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '11',
    name: 'Logitech G-Series Gaming Mouse',
    image: '/images/mouse.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 5000,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '12',
    name: 'Amazon Echo Dot 3rd Generation',
    image: '/images/alexa.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: 2500,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
   
]

export default products
